const aerodromes = [
    { name: "aberdeen", alt: "dyce", icao: "egpd" },
    { name: "aberporth", icao: "eguc" },
    { name: "alderney", icao: "egja" },
    { name: "alscot", icao: "egbl" },
    { name: "andrew (oil rig)", icao: "egro" },
    { name: "andrewsfield", icao: "egsl" },
    { name: "antarctic sky-blu", icao: "egat" },
    { name: "ascot heliport", icao: "eglt" },
    { name: "isle of skye", alt: "ashaig", icao: "egei" },
    { name: "ashcroft", icao: "egcr" },
    { name: "bagby", icao: "egng" },
    { name: "barkston heath", icao: "egye" },
    { name: "barra", icao: "egpr" },
    { name: "beccles", icao: "egsm" },
    { name: "bedford", icao: "egbf" },
    { name: "belfast aldergrove", icao: "egaa" },
    { name: "belfast city", icao: "egac" },
    { name: "bembridge", icao: "eghj" },
    { name: "benbecula", icao: "egpl" },
    { name: "benbecula (mod)", icao: "egxm" },
    { name: "benson", icao: "egub" },
    { name: "beverley", alt: "linley hill", icao: "egny" },
    { name: "biggin hill", icao: "egkb" },
    { name: "birmingham", icao: "egbb" },
    { name: "blackbushe", icao: "eglk" },
    { name: "blackpool", icao: "egnh" },
    { name: "bodmin", icao: "egla" },
    { name: "boscombe down", icao: "egdm" },
    { name: "boulmer (mod)", icao: "egqm" },
    { name: "bournemouth", icao: "eghh" },
    { name: "brampton (mod)", icao: "egyb" },
    { name: "brimpton", icao: "eglp" },
    { name: "bristol", icao: "eggd" },
    { name: "brize norton", icao: "egvn" },
    { name: "brooklands", icao: "eglb" },
    { name: "brough", icao: "egnb" },
    { name: "bruce (oil rig)", icao: "egrk" },
    { name: "cacc mid east", icao: "egif" },
    { name: "cacc mid west", icao: "egie" },
    { name: "cacc north east", icao: "egid" },
    { name: "cacc north west", icao: "egic" },
    { name: "cacc scotland/northern ireland", icao: "egia" },
    { name: "cacc south east", icao: "egih" },
    { name: "cacc south west", icao: "egig" },
    { name: "cacc wales", icao: "egib" },
    { name: "caernarfon", icao: "egck" },
    { name: "cambridge", icao: "egsc" },
    { name: "campbeltown", icao: "egec" },
    { name: "cardiff", icao: "egff" },
    { name: "cardiff/tremorfa foreshore heliport", icao: "egfc" },
    { name: "carlisle", icao: "egnc" },
    { name: "chalgrove", icao: "eglj" },
    { name: "challock", icao: "egke" },
    { name: "channel islands", icao: "egjt" },
    { name: "cheltenham heliport", icao: "egbc" },
    { name: "chichester/goodwood", icao: "eghr" },
    { name: "clacton", icao: "egsq" },
    { name: "clair (oil rig)", icao: "egrf" },
    { name: "cleeton (oil rig)", icao: "egrt" },
    { name: "colerne", icao: "eguo" },
    { name: "coll", icao: "egel" },
    { name: "colonsay", icao: "egey" },
    { name: "compton abbas", icao: "egha" },
    { name: "coningsby", icao: "egxc" },
    { name: "cormorant alpha (oil rig)", icao: "egrg" },
    { name: "cosford", icao: "egwc" },
    { name: "cottesmore", icao: "egxj" },
    { name: "coventry", icao: "egbe" },
    { name: "cranfield", icao: "egtc" },
    { name: "cranwell", icao: "egyd" },
    { name: "crowfield", icao: "egso" },
    { name: "culdrose", icao: "egdr" },
    { name: "culter helipad", icao: "egea" },
    { name: "cumbernauld", icao: "egpg" },
    { name: "damyns hall", icao: "egml" },
    { name: "deanland", icao: "egkl" },
    { name: "denham", icao: "egld" },
    { name: "derby", icao: "egbd" },
    { name: "dishforth", icao: "egxd" },
    { name: "doncaster sheffield", icao: "egcn" },
    { name: "donna nook (mod)", icao: "egxs" },
    { name: "dundee", icao: "egpn" },
    { name: "dunkeswell", icao: "egtu" },
    { name: "dunsfold", icao: "egtd" },
    { name: "duxford", icao: "egsu" },
    { name: "eaglescott", icao: "eghu" },
    { name: "earls colne", icao: "egsr" },
    { name: "east midlands", icao: "egnx" },
    { name: "eday", icao: "eged" },
    { name: "edinburgh", icao: "egph" },
    { name: "elmsett", icao: "egst" },
    { name: "elstree", icao: "egtr" },
    { name: "enniskillen/st angelo", icao: "egab" },
    { name: "enstone", icao: "egtn" },
    { name: "exeter", icao: "egte" },
    { name: "fair isle", icao: "egef" },
    { name: "fairford", icao: "egva" },
    { name: "fairoaks", icao: "egtf" },
    { name: "farnborough", icao: "eglf" },
    { name: "farthing corner", icao: "egmf" },
    { name: "faslane (mod)", icao: "egxo" },
    { name: "fenland", icao: "egcl" },
    { name: "fife", icao: "egpj" },
    { name: "forest moor", icao: "egxf" },
    { name: "fowlmere", icao: "egma" },
    { name: "full sutton", icao: "egnu" },
    { name: "fulmar alpha (oil rig)", icao: "egrn" },
    { name: "garvie island (mod)", icao: "egqc" },
    { name: "gatwick caa srg (aviation house)", icao: "eggr" },
    { name: "glasgow", icao: "egpf" },
    { name: "glasgow city heliport", icao: "egeg" },
    { name: "glasgow weather centre", icao: "egra" },
    { name: "gloucestershire", icao: "egbj" },
    { name: "goodwood racecourse heliport", icao: "egkg" },
    { name: "guernsey", icao: "egjb" },
    { name: "halley research station", icao: "egah" },
    { name: "halton", icao: "egwn" },
    { name: "harding (oil rig)", icao: "egrl" },
    { name: "haverfordwest", icao: "egfe" },
    { name: "hawarden", icao: "egnr" },
    { name: "henstridge", icao: "eghs" },
    { name: "hereford", icao: "egvh" },
    { name: "high wycombe (met)", icao: "egrh" },
    { name: "high wycombe (mod)", icao: "eguh" },
    { name: "hm ships (all)", icao: "egyy" },
    { name: "holbeach (mod)", icao: "egyh" },
    { name: "honington", icao: "egxh" },
    { name: "hq 2 group (mod)", icao: "egdh" },
    { name: "hq spta", icao: "egds" },
    { name: "hucknall", icao: "egna" },
    { name: "humberside", icao: "egnj" },
    { name: "inverness", icao: "egpe" },
    { name: "islay", icao: "egpi" },
    { name: "isle of man", icao: "egns" },
    { name: "isle of wight/sandown", icao: "eghn" },
    { name: "isleworth", icao: "egli" },
    { name: "jersey", icao: "egjj" },
    { name: "jersey met", icao: "egjx" },
    { name: "kemble", icao: "egbp" },
    { name: "kenley (mod)", icao: "egkn" },
    { name: "kinloss", icao: "egqk" },
    { name: "kirknewton (mod)", icao: "egkt" },
    { name: "kirkwall", icao: "egpa" },
    { name: "lakenheath", icao: "egul" },
    { name: "land's end", icao: "eghc" },
    { name: "langford lodge", icao: "egal" },
    { name: "lasham", icao: "eghl" },
    { name: "lashenden/headcorn", icao: "egkh" },
    { name: "leconfield", icao: "egxv" },
    { name: "lee-on-solent", icao: "eghf" },
    { name: "leeds bradford", icao: "egnm" },
    { name: "leeds east", icao: "egcm" },
    { name: "leeds heliport", icao: "egnp" },
    { name: "leeming", icao: "egxe" },
    { name: "leicester", icao: "egbg" },
    { name: "lerwick/tingwall", icao: "eget" },
    { name: "leuchars", icao: "egql" },
    { name: "little gransden", icao: "egmj" },
    { name: "little rissington", icao: "egvl" },
    { name: "liverpool", icao: "eggp" },
    { name: "llanbedr", icao: "egfd" },
    { name: "london (caa hq)", icao: "egga" },
    { name: "london (dft aviation directorate)", icao: "eggc" },
    { name: "london acc (civil)", icao: "egtt" },
    { name: "london area", icao: "eggo" },
    { name: "london city", icao: "eglc" },
    { name: "london gatwick", icao: "egkk" },
    { name: "london heathrow", icao: "egll" },
    { name: "london heliport", icao: "eglw" },
    { name: "london luton", icao: "eggw" },
    { name: "london stansted", icao: "egss" },
    { name: "londonderry/eglinton", icao: "egae" },
    { name: "lossiemouth", icao: "egqs" },
    { name: "lowestoft harbour", icao: "egmw" },
    { name: "lydd", icao: "egmd" },
    { name: "lyneham", icao: "egdl" },
    { name: "magnus (oil rig)", icao: "egre" },
    { name: "manchester", icao: "egcc" },
    { name: "manchester barton", icao: "egcb" },
    { name: "manchester/woodford", icao: "egcd" },
    { name: "manston", icao: "egmh" },
    { name: "marham", icao: "egym" },
    { name: "marnock (oil rig)", icao: "egrs" },
    { name: "marshland, wisbeach", icao: "egsi" },
    { name: "maypole", icao: "eghb" },
    { name: "mca falmouth", icao: "egqf" },
    { name: "merryfield", icao: "egdi" },
    { name: "met office aberdeen", icao: "egrq" },
    { name: "met office exeter", icao: "egrr" },
    { name: "met office london", icao: "egrb" },
    { name: "middle wallop", icao: "egvp" },
    { name: "mildenhall", icao: "egun" },
    { name: "miller (oil rig)", icao: "egrm" },
    { name: "mod uk air", icao: "egwb" },
    { name: "mod uk navy", icao: "egwi" },
    { name: "mount pleasant", icao: "egyp" },
    { name: "mountwise", icao: "egdb" },
    { name: "muharraq (raf)", icao: "egyr" },
    { name: "mungo (oil rig)", icao: "egrp" },
    { name: "murdoch (oil rig)", icao: "egru" },
    { name: "neatishead (mod)", icao: "eguj" },
    { name: "netheravon", icao: "egdn" },
    { name: "netherthorpe", icao: "egnf" },
    { name: "newcastle", icao: "egnt" },
    { name: "newmarket racecourse", icao: "egsw" },
    { name: "newquay", icao: "eghq" },
    { name: "newtownards", icao: "egad" },
    { name: "north ronaldsay", icao: "egen" },
    { name: "north weald", icao: "egsx" },
    { name: "sywell", alt: "northampton", icao: "egbk" },
    { name: "northolt", icao: "egwu" },
    { name: "northolt (aidu)", icao: "egvc" },
    { name: "northolt (rn naic)", icao: "egxa" },
    { name: "northwood (mod)", icao: "egwx" },
    { name: "norwich", icao: "egsh" },
    { name: "nottingham", icao: "egbn" },
    { name: "oaksey park", icao: "egtw" },
    { name: "oban", icao: "egeo" },
    { name: "odiham", icao: "egvo" },
    { name: "old buckenham", icao: "egsv" },
    { name: "old sarum", icao: "egls" },
    { name: "old warden", icao: "egth" },
    { name: "oxford", icao: "egtk" },
    { name: "papa westray", icao: "egep" },
    { name: "pembrey", icao: "egfp" },
    { name: "pembry (mod)", icao: "egop" },
    { name: "penzance heliport", icao: "eghk" },
    { name: "perranporth", icao: "egtp" },
    { name: "perth", alt: "scone", icao: "egpt" },
    { name: "peterborough/conington", icao: "egsf" },
    { name: "peterborough/sibson", icao: "egsp" },
    { name: "peterhead/longside heliport", icao: "egps" },
    { name: "plymouth (mil)", icao: "egve" },
    { name: "popham", icao: "eghp" },
    { name: "portland heliport", icao: "egdp" },
    { name: "fleetlands", icao: "egvf" },
    { name: "predannack", icao: "egdo" },
    { name: "prestwick", icao: "egpk" },
    { name: "raf mobiles", icao: "egww" },
    { name: "raf mona", icao: "egoq" },
    { name: "raleigh (mod)", icao: "egvr" },
    { name: "ravenspurn n (oil rig)", icao: "egrv" },
    { name: "redhill", icao: "egkr" },
    { name: "gamston", alt: "retford", icao: "egne" },
    { name: "rochester", icao: "egto" },
    { name: "rothera research station", icao: "egar" },
    { name: "sanday", icao: "eges" },
    { name: "sandtoft", icao: "egcf" },
    { name: "schiehallion (oil rig)", icao: "egri" },
    { name: "scilly isles", alt: "st mary's", icao: "eghe" },
    { name: "scottish acc (civil)", icao: "egpx" },
    { name: "seething", icao: "egsj" },
    { name: "shanwick oac", icao: "eggx" },
    { name: "shawbury", icao: "egos" },
    { name: "sherburn-in-elmet", icao: "egcj" },
    { name: "shipdham", icao: "egsa" },
    { name: "shobdon", icao: "egbs" },
    { name: "shoreham", alt: "Brighton City", icao: "egka" },
    { name: "silverstone heliport", icao: "egbv" },
    { name: "sleap", icao: "egcv" },
    { name: "south cerney (mod)", icao: "egcy" },
    { name: "southampton", icao: "eghi" },
    { name: "southend", icao: "egmc" },
    { name: "southport birkdale sands", icao: "egco" },
    { name: "spadeadam (mod)", icao: "egom" },
    { name: "st athan", icao: "egsy" },
    { name: "stapleford", icao: "egsg" },
    { name: "stornoway", icao: "egpo" },
    { name: "stronsay", icao: "eger" },
    { name: "strubby heliport", icao: "egcg" },
    { name: "sturgate", icao: "egcs" },
    { name: "sumburgh", icao: "egpb" },
    { name: "swansea", icao: "egfh" },
    { name: "swanton morley (mod)", icao: "egyx" },
    { name: "swanwick atcc (mil)", icao: "egvv" },
    { name: "syerston (mod)", icao: "egxy" },
    { name: "tain (mod)", icao: "egqa" },
    { name: "tatenhill", icao: "egbm" },
    { name: "teesside", icao: "egnv" },
    { name: "ternhill", icao: "egoe" },
    { name: "thorne", icao: "egcp" },
    { name: "thruxton", icao: "egho" },
    { name: "thurrock", icao: "egmt" },
    { name: "tilstock", icao: "egct" },
    { name: "tiree", icao: "egpu" },
    { name: "topcliffe", icao: "egxz" },
    { name: "tresco heliport", icao: "eght" },
    { name: "truro", icao: "eghy" },
    { name: "turweston", icao: "egbt" },
    { name: "unst", icao: "egpw" },
    { name: "uxbridge", icao: "eguu" },
    { name: "valley", icao: "egov" },
    { name: "waddington", icao: "egxw" },
    { name: "walney", icao: "egnl" },
    { name: "warton", icao: "egno" },
    { name: "wattisham", icao: "eguw" },
    { name: "wellesbourne mountford", icao: "egbw" },
    { name: "welshpool", icao: "egcw" },
    { name: "west freugh", icao: "egoy" },
    { name: "west sole (oil rig)", icao: "egrw" },
    { name: "aberporth", alt: "west wales", icao: "egfa" },
    { name: "westray", icao: "egew" },
    { name: "whalsey", icao: "egeh" },
    { name: "white waltham", icao: "eglm" },
    { name: "wick", icao: "egpc" },
    { name: "wickenby", icao: "egnw" },
    { name: "wittering", icao: "egxt" },
    { name: "wolverhampton", alt: "halfpenny green", icao: "egbo" },
    { name: "woodvale", icao: "egow" },
    { name: "wycombe air park", alt: "booker", icao: "egtb" },
    { name: "wyton", icao: "eguy" },
    { name: "yeovil/westland", icao: "eghg" },
    { name: "yeovilton", icao: "egdy" }
]

Object.hasOwn()